// frontend/src/components/miniplayer.tsx
import { ReactComponent as NavUp } from "../assets/nav-up.svg";
import { ReactComponent as NextIcon } from "../assets/control-next.svg";
import { ReactComponent as PlayIcon } from "../assets/control-play-outline.svg";
import { Link } from "react-router-dom";

export default function Miniplayer() {
  return (
    <div className="p-4 h-16 flex items-center border-t">
      <Link to="/player">
        <NavUp />
      </Link>

      <img className="mx-2 border h-12" src="logo192.png" alt="cover art"></img>
      <span className="m-2 text-left flex-grow">Miniplayer</span>
      <span>0:00</span>
      <div className="m-4 flex flex-row">
        <PlayIcon className="h-10 w-10 text-primary" />
        <NextIcon className="h-10 w-10 text-primary" />
      </div>
    </div>
  );
}

// frontend/components/MiniPlayer.vue
<template>
  <div class="p-4 h-16 border-t flex justify-between items-center">
    <nuxt-link to="/player"
      ><nav-up-icon class="h-6 w-6 text-primary"
    /></nuxt-link>
    {{ current_title }}
    <span class="w-6" />
  </div>
</template>
<script>
import { mapGetters } from 'vuex'
import NavUpIcon from '~/assets/nav-back.svg?inline'

export default {
  components: { NavUpIcon },
  computed: {
    ...mapGetters('players', ['current_title']),
  },
}
</script>
